services:
  app:
    image: localhost/teguhyuhono/satria-aii:arm
    container_name: satria-aii-app
    ports:
      - "8082:80"
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - LOG_CHANNEL=stderr
      - DB_HOST=satria-aii-db
      - DB_PORT=3306
      - DB_DATABASE=SATRIA_AII
      - DB_USERNAME=root
      - DB_PASSWORD=secret
      - SESSION_DRIVER=file
    networks:
      - satria-network
    volumes:
      - ./:/var/www/html
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s
  db:
    image: mysql:8.0
    container_name: satria-aii-db
    networks:
      - satria-network
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=SATRIA_AII
    volumes:
      - db_data:/var/lib/mysql

networks:
  satria-network:
    driver: bridge
volumes:
  db_data: